/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import DAO.FinanceiroPagarDAO;
import DAO.FinanceiroReceberDAO;
import apoio.Formatacao;
import apoio.Validacao;
import entidade.Cidade;
import entidade.FinanceiroPagar;
import entidade.FinanceiroReceber;
import entidade.FormaPagamento;
import entidade.Fornecedor;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mileto
 */
public class JdgCadastroFinanceiroPagar extends javax.swing.JDialog {

    /**
     * Creates new form JdgCadastroFinanceiroReceber
     */
    FinanceiroPagar formaPagamentoPagas;
    
    public JdgCadastroFinanceiroPagar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        formaPagamentoPagas = new FinanceiroPagar();
        bloquearCampos();
    }
    
    public JdgCadastroFinanceiroPagar(java.awt.Frame parent, boolean modal, FinanceiroPagar formaPagamentoPagas) throws ParseException {
        super(parent, modal);
        initComponents();
        
        this.formaPagamentoPagas = formaPagamentoPagas;
        listarTitulo();
        bloquearCampos();
        
    }
    
    private void bloquearCampos() {
        try {
            if (formaPagamentoPagas.getId() > 0) {
                tfdNumeroTitulo.setEnabled(false);
                tffDataVencimento.setEnabled(false);
                try {
                    if (Double.parseDouble(tffValor.getText()) > 0) {
                        tffValor.setEnabled(false);
                        btnConfirmar.setEnabled(false);
                    } else {
                        tffValor.setEnabled(true);
                        btnConfirmar.setEnabled(true);
                    }
                    
                } catch (Exception e) {
                    tffValor.setEnabled(true);
                    btnConfirmar.setEnabled(true);
                }
                
                btnExcluir.setEnabled(true);
                btnLocalizarCliente.setEnabled(false);
                btnLocalizarFormaDePagamento.setEnabled(false);
                
                tffValorPrevisto.setEnabled(false);
                tffValorAReceber.setEditable(true);
                
            } else {
                tfdNumeroTitulo.setEnabled(true);
                tffValor.setEnabled(true);
                tffDataVencimento.setEnabled(true);
                
                btnExcluir.setEnabled(false);
                btnLocalizarCliente.setEnabled(true);
                btnLocalizarFormaDePagamento.setEnabled(true);
                btnConfirmar.setEnabled(true);
                btnExcluir.setEnabled(false);
                btnPagarTitulo.setEnabled(false);
                tffValorPrevisto.setEnabled(true);
                
            }
        } catch (Exception e) {
            tfdNumeroTitulo.setEditable(true);
            tffValor.setEnabled(true);
            tffDataVencimento.setEnabled(true);
            
            btnExcluir.setEnabled(true);
            btnLocalizarCliente.setEnabled(true);
            btnLocalizarFormaDePagamento.setEnabled(true);
            btnConfirmar.setEnabled(true);
            btnExcluir.setEnabled(false);
            btnPagarTitulo.setEnabled(false);
            tffValorPrevisto.setEditable(true);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void listarTitulo() throws ParseException {
        tffValorAReceber.setText("");
        tfdCodigo.setText(String.valueOf(formaPagamentoPagas.getId()));
        tfdNumeroTitulo.setText(formaPagamentoPagas.getNumeroTitulo());
        tffValorPrevisto.setText(String.valueOf(formaPagamentoPagas.getValorProvisorio()));
        tffValor.setText(String.valueOf(formaPagamentoPagas.getValor()));
        tfdValorPago.setText(String.valueOf(formaPagamentoPagas.getValorPago()));
        tfdFornecedorNome.setText(formaPagamentoPagas.getFornecedor().getRazaoSocial());
        tfdFormaPagamentoNome.setText(formaPagamentoPagas.getFormaPagamento().getDescricao());
        tfdValorPago.setText(String.valueOf(formaPagamentoPagas.getValorPago()));
        //tffDataVencimento.setToolTipText(String.valueOf(formaPagamentoPagas.getVencimento()));

        //String strDate = "01/07/1990";
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Calendar c = Calendar.getInstance();
        c.setTime(sdf.parse(formaPagamentoPagas.getVencimento()));
        tffDataVencimento.setCalendar(c);
        if (formaPagamentoPagas.getQuitado() == 'T') {
            tfdSituacao.setText("QUITADO");
            tffValorAReceber.setEnabled(false);
            
            btnPagarTitulo.setEnabled(false);
            
        } else {
            tfdSituacao.setText("EM ABERTO");
            tffValorAReceber.setEnabled(true);
        }
        tfdDataEmissao.setText(formaPagamentoPagas.getDataEmissao());
        tfdDataPagamento.setText(formaPagamentoPagas.getDataPagamento());
        //tffDataVencimento.setText(formaPagamentoPagas.getVencimento());

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        lblNumeroTitulo = new javax.swing.JLabel();
        lblFornecedor = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lblFormaDePagamento = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfdCodigo = new javax.swing.JTextField();
        tfdNumeroTitulo = new javax.swing.JTextField();
        tfdFornecedorNome = new javax.swing.JTextField();
        tfdFormaPagamentoNome = new javax.swing.JTextField();
        tfdSituacao = new javax.swing.JTextField();
        lblDataEmissao = new javax.swing.JLabel();
        lblDataVencimento = new javax.swing.JLabel();
        lblDataPagamento = new javax.swing.JLabel();
        tfdDataEmissao = new javax.swing.JTextField();
        tfdDataPagamento = new javax.swing.JTextField();
        btnPagarTitulo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblValorAReceber = new javax.swing.JLabel();
        tffValorAReceber = new javax.swing.JFormattedTextField();
        lblValorPago = new javax.swing.JLabel();
        tfdValorPago = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        btnLocalizarCliente = new javax.swing.JButton();
        btnLocalizarFormaDePagamento = new javax.swing.JButton();
        lblValorPrevisto = new javax.swing.JLabel();
        tffValorPrevisto = new javax.swing.JFormattedTextField();
        tffDataVencimento = new com.toedter.calendar.JDateChooser();
        tffValor = new javax.swing.JFormattedTextField();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro Título a pagar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 51, 255))); // NOI18N

        lblCodigo.setText("Código:");

        lblNumeroTitulo.setText("N° Título:");

        lblFornecedor.setText("Fornecedor:");

        lblValor.setText("Valor:");

        lblFormaDePagamento.setText("Forma de pagamento:");

        jLabel6.setText("Situação:");

        tfdCodigo.setEnabled(false);

        tfdFornecedorNome.setEditable(false);

        tfdFormaPagamentoNome.setEditable(false);

        tfdSituacao.setEditable(false);

        lblDataEmissao.setText("Data Emissao:");

        lblDataVencimento.setText("Data Vencimento:");

        lblDataPagamento.setText("Data pagamento:");

        tfdDataEmissao.setEditable(false);

        tfdDataPagamento.setEditable(false);

        btnPagarTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Icon_money.png"))); // NOI18N
        btnPagarTitulo.setText("Pagar Título");
        btnPagarTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarTituloActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_Schutdown16.png"))); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblValorAReceber.setText("Valor a receber:");

        tffValorAReceber.setEditable(false);
        tffValorAReceber.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        lblValorPago.setText("Valor pago:");

        tfdValorPago.setEditable(false);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_button_cancel.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnLocalizarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Lupa3.png"))); // NOI18N
        btnLocalizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizarClienteActionPerformed(evt);
            }
        });

        btnLocalizarFormaDePagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Lupa3.png"))); // NOI18N
        btnLocalizarFormaDePagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizarFormaDePagamentoActionPerformed(evt);
            }
        });

        lblValorPrevisto.setText("Valor previsto:");

        tffDataVencimento.setToolTipText("");
        tffDataVencimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tffDataVencimentoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPagarTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblFormaDePagamento)
                                        .addComponent(lblValorAReceber))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tffValorAReceber, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(tfdFormaPagamentoNome)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnLocalizarFormaDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblFornecedor)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfdFornecedorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnLocalizarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblValorPrevisto)
                                            .addComponent(lblValorPago))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfdValorPago, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                            .addComponent(tffValorPrevisto)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblValor)
                                            .addComponent(lblNumeroTitulo)
                                            .addComponent(lblCodigo))
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfdCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                            .addComponent(tfdNumeroTitulo)
                                            .addComponent(tffValor))))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDataVencimento)
                                            .addComponent(lblDataPagamento)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfdDataPagamento)
                                            .addComponent(tfdSituacao)
                                            .addComponent(tffDataVencimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblDataEmissao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                        .addComponent(tfdDataEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdNumeroTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumeroTitulo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValor)
                            .addComponent(tffValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValorPrevisto)
                            .addComponent(tffValorPrevisto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDataEmissao)
                            .addComponent(tfdDataEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDataVencimento)
                            .addComponent(tffDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDataPagamento)
                            .addComponent(tfdDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfdSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValorPago))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFornecedor)
                            .addComponent(tfdFornecedorNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLocalizarCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFormaDePagamento)
                            .addComponent(tfdFormaPagamentoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnLocalizarFormaDePagamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorAReceber)
                    .addComponent(tffValorAReceber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnPagarTitulo)
                    .addComponent(btnExcluir)
                    .addComponent(btnConfirmar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPagarTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarTituloActionPerformed
        //if (Double.parseDouble(tffValorAReceber.getText().replace(",", "."))>0) {
        formaPagamentoPagas.setAtivo('T');
        try {
            if (Double.parseDouble(tffValor.getText()) > 0) {
                formaPagamentoPagas.setValor(Double.parseDouble(tffValor.getText()));
                pagarTitulo();
            } else {
                JOptionPane.showMessageDialog(rootPane, "1 Erro ao efetuar o pagamento do título: \n é preciso que o título tenha um valor maior que zero.");
            }
            
        } catch (Exception e) {
            //   JOptionPane.showMessageDialog(rootPane, "É preciso informar um valor para pagar o título");
            JOptionPane.showMessageDialog(rootPane, " Erro ao efetuar o pagamento do título: \n é preciso que o título tenha um valor maior que zero.");
        }
        
        try {
            listarTitulo();
        } catch (ParseException ex) {
            Logger.getLogger(JdgCadastroFinanceiroPagar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPagarTituloActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
//        tfdNumeroTitulo.setEditable(true);
//            tfdValorPago.setEditable(true);
//            tfdDataVencimento.setEditable(true);
//            tfdDataEmissao.setEditable(true);
//            tfdValor.setEditable(true);
//            btnLocalizarCliente.setEnabled(true);
//            btnLocalizarFormaDePagamento.setEnabled(true);
//            btnPagarTitulo.setEnabled(false);
//            btnExcluir.setEnabled(false);
//            btnIncluir.setText("Confirmar");
//            btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png")));
        formaPagamentoPagas.setAtivo('T');
        if (formaPagamentoPagas.getId() == 0) {
            formaPagamentoPagas.setNumeroTitulo(tfdNumeroTitulo.getText());
            FinanceiroPagarDAO financeiroPagarDAO = new FinanceiroPagarDAO();
            ArrayList<FinanceiroPagar> arrayFormasPagas;
            arrayFormasPagas = financeiroPagarDAO.consultar(formaPagamentoPagas);
            
            lblFornecedor.setForeground(Color.black);
            lblFormaDePagamento.setForeground(Color.black);
            lblValorPrevisto.setForeground(Color.black);
            lblDataVencimento.setForeground(Color.black);
            lblNumeroTitulo.setForeground(Color.black);
            
            if (arrayFormasPagas.size() > 0) {
                // bloquearCampos();
                JOptionPane.showMessageDialog(rootPane, "Erro ao salvar título: Número de título já utilizado em outro cadastro.");
                lblNumeroTitulo.setForeground(Color.red);
                
            } else {
                
                if (validarCampos()) {
                    Date data = new Date();
                    data.setDate(data.getDate());
                    String dataFormatada = Formatacao.ajustaDataDMAJCalendar(data);
                    formaPagamentoPagas.setNumeroTitulo(tfdNumeroTitulo.getText());
                    formaPagamentoPagas.setValorProvisorio(Double.parseDouble(tffValorPrevisto.getText()));
                    
                    if (tffValor.getText() != "") {
                        try {
                            formaPagamentoPagas.setValor(Double.parseDouble(tffValor.getText()));
                        } catch (Exception e) {
                            formaPagamentoPagas.setValor(0);
                        }
                    } else {
                        formaPagamentoPagas.setValor(0);
                    }
                    //formaPagamentoPagas.setDataEmissao(dataFormatada);
                    formaPagamentoPagas.setDataEmissao(Formatacao.getDataAtual());
                    //formaPagamentoPagas.setDataEmissao("20/10/2017 23:23:23");
                    formaPagamentoPagas.setAtivo('T');
                    
                    formaPagamentoPagas.setQuitado('F');
                    if (financeiroPagarDAO.salvar(formaPagamentoPagas)) {
                        JOptionPane.showMessageDialog(rootPane, "Título cadastrado com sucesso");
                        dispose();
                        bloquearCampos();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Erro ao salvar título");
                    }
                    
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Erro ao salvar título, campos nulos ou inválidos");
                    
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "id maior que zero");
            try {
                formaPagamentoPagas.setValor(Double.parseDouble(tffValor.getText()));
                FinanceiroPagarDAO financeiroPagarDAO = new FinanceiroPagarDAO();
                if (financeiroPagarDAO.salvar(formaPagamentoPagas)) {
                    JOptionPane.showMessageDialog(rootPane, "Título salvo com sucesso");
                    bloquearCampos();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Erro ao salvar título");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao salvar título");
            }
            
        }

        //bloquearCampos();

    }//GEN-LAST:event_btnConfirmarActionPerformed
    private boolean validarCampos() {
        
        boolean ok = true;
        if (tfdFornecedorNome.getText().equals("")) {
            ok = false;
            lblFornecedor.setForeground(Color.red);
        }
        if (tfdFormaPagamentoNome.getText().equals("")) {
            ok = false;
            lblFormaDePagamento.setForeground(Color.red);
        }
        
        if (tffValorPrevisto != null) {
            try {
                if (Double.parseDouble(tffValorPrevisto.getText()) <= 0) {
                    ok = false;
                    lblValorPrevisto.setForeground(Color.red);
                    
                }
            } catch (Exception e) {
                ok = false;
                lblValorPrevisto.setForeground(Color.red);
            }
        } else {
            ok = false;
            lblValorPrevisto.setForeground(Color.red);
        }
        
        if (tffDataVencimento.getCalendar() != null) {
            try {
                if (Validacao.validadeFiltroDeData(tffDataVencimento)) {
                    formaPagamentoPagas.setVencimento(Formatacao.ajustaDataDMAJCalendar(tffDataVencimento));
                } else {
                    ok = false;
                    lblDataVencimento.setForeground(Color.red);
                }
            } catch (Exception e) {
                ok = false;
                lblDataVencimento.setForeground(Color.red);
            }
        } else {
            ok = false;
            lblDataVencimento.setForeground(Color.red);
        }
        if (tfdNumeroTitulo.getText().equals("")) {
            ok = false;
            lblNumeroTitulo.setForeground(Color.red);
        }
        
        return ok;
    }
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        formaPagamentoPagas.setAtivo('F');
        Date data = new Date();
        data.setDate(data.getDate());
        String dataFormatada = Formatacao.ajustaDataDMAJCalendar(data);
        formaPagamentoPagas.setDataPagamento(dataFormatada);
        
        FinanceiroPagarDAO financeiroPagamentoDAO = new FinanceiroPagarDAO();
        int retorno = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que quer excluir o título\n número :" + formaPagamentoPagas.getNumeroTitulo() + "\n"
                + " de valor: " + formaPagamentoPagas.getValor());
        if (retorno == 0) {
            if (financeiroPagamentoDAO.salvar(formaPagamentoPagas)) {
                JOptionPane.showMessageDialog(rootPane, "Título excluído com sucesso!");
                dispose();
                
            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro ao excluir o título");
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tffDataVencimentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tffDataVencimentoKeyReleased

    }//GEN-LAST:event_tffDataVencimentoKeyReleased

    private void btnLocalizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizarClienteActionPerformed
        Cidade cid = new Cidade();
        Fornecedor fornecedor = new Fornecedor(cid);
        JdgListaFornecedor listaFornecedor = new JdgListaFornecedor(null, true, fornecedor, cid);
        listaFornecedor.setVisible(true);
        formaPagamentoPagas.setFornecedor(fornecedor);
        tfdFornecedorNome.setText(formaPagamentoPagas.getFornecedor().getRazaoSocial());
    }//GEN-LAST:event_btnLocalizarClienteActionPerformed

    private void btnLocalizarFormaDePagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizarFormaDePagamentoActionPerformed
        FormaPagamento formaPagamento = new FormaPagamento();
        try {
            JdgListaFormaPagamento listaFormaPagamento = new JdgListaFormaPagamento(null, true, formaPagamento);
            listaFormaPagamento.setVisible(true);
            tfdFormaPagamentoNome.setText(formaPagamento.getDescricao());
            formaPagamentoPagas.setFormaPagamento(formaPagamento);
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_btnLocalizarFormaDePagamentoActionPerformed
    private void pagarTitulo() {
        if ((Double.parseDouble(tffValorAReceber.getText().replace(",", "."))) + (Double.parseDouble(tfdValorPago.getText().replace(",", "."))) >= Double.parseDouble(tffValor.getText().replace(",", "."))) {
            formaPagamentoPagas.setQuitado('T');
            formaPagamentoPagas.setValorPago((Double.parseDouble(tffValorAReceber.getText().replace(",", "."))) + (Double.parseDouble(tfdValorPago.getText().replace(",", "."))));
            Date data = new Date();
            data.setDate(data.getDate());
            String dataFormatada = Formatacao.ajustaDataDMAJCalendar(data);
            formaPagamentoPagas.setDataPagamento(dataFormatada);
            FinanceiroPagarDAO financeiroPagamentoDAO = new FinanceiroPagarDAO();
            
            if (financeiroPagamentoDAO.salvar(formaPagamentoPagas)) {
                JOptionPane.showMessageDialog(rootPane, "Pagamento do título registrado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro ao salvar pagamento do título");
            }
            
        } else {
            
            formaPagamentoPagas.setValorPago((Double.parseDouble(tffValorAReceber.getText().replace(",", "."))) + (Double.parseDouble(tfdValorPago.getText().replace(",", "."))));
            Date data = new Date();
            data.setDate(data.getDate());
            String dataFormatada = Formatacao.ajustaDataDMAJCalendar(data);
            formaPagamentoPagas.setDataPagamento(dataFormatada);
            FinanceiroPagarDAO financeiroPagamentoDAO = new FinanceiroPagarDAO();
            if (tffValor.getText() != "") {
                try {
                    formaPagamentoPagas.setValor(Double.parseDouble(tffValor.getText()));
                } catch (Exception e) {
                    formaPagamentoPagas.setValor(0);
                }
            } else {
                formaPagamentoPagas.setValor(0);
            }
            if (financeiroPagamentoDAO.salvar(formaPagamentoPagas)) {
                JOptionPane.showMessageDialog(rootPane, "Pagamento do título registrado com sucesso!");
                tffValorAReceber.setText("");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro ao salvar pagamento do título");
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JdgCadastroFinanceiroPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JdgCadastroFinanceiroPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JdgCadastroFinanceiroPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JdgCadastroFinanceiroPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JdgCadastroFinanceiroPagar dialog = new JdgCadastroFinanceiroPagar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLocalizarCliente;
    private javax.swing.JButton btnLocalizarFormaDePagamento;
    private javax.swing.JButton btnPagarTitulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDataEmissao;
    private javax.swing.JLabel lblDataPagamento;
    private javax.swing.JLabel lblDataVencimento;
    private javax.swing.JLabel lblFormaDePagamento;
    private javax.swing.JLabel lblFornecedor;
    private javax.swing.JLabel lblNumeroTitulo;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblValorAReceber;
    private javax.swing.JLabel lblValorPago;
    private javax.swing.JLabel lblValorPrevisto;
    private javax.swing.JTextField tfdCodigo;
    private javax.swing.JTextField tfdDataEmissao;
    private javax.swing.JTextField tfdDataPagamento;
    private javax.swing.JTextField tfdFormaPagamentoNome;
    private javax.swing.JTextField tfdFornecedorNome;
    private javax.swing.JTextField tfdNumeroTitulo;
    private javax.swing.JTextField tfdSituacao;
    private javax.swing.JTextField tfdValorPago;
    private com.toedter.calendar.JDateChooser tffDataVencimento;
    private javax.swing.JFormattedTextField tffValor;
    private javax.swing.JFormattedTextField tffValorAReceber;
    private javax.swing.JFormattedTextField tffValorPrevisto;
    // End of variables declaration//GEN-END:variables
}
