/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import DAO.FinanceiroReceberDAO;
import apoio.Formatacao;
import entidade.FinanceiroReceber;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Mileto
 */
public class JdgCadastroFinanceiroReceber extends javax.swing.JDialog {

    /**
     * Creates new form JdgCadastroFinanceiroReceber
     */
    FinanceiroReceber formaPagamentoPagas;

    public JdgCadastroFinanceiroReceber(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JdgCadastroFinanceiroReceber(java.awt.Frame parent, boolean modal, FinanceiroReceber formaPagamentoPagas) {
        super(parent, modal);
        initComponents();

        this.formaPagamentoPagas = formaPagamentoPagas;
        listarTitulo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void listarTitulo() {
        tffValorAReceber.setText("");
        tfdCodigo.setText(String.valueOf(formaPagamentoPagas.getId()));
        tfdNumeroTitulo.setText(formaPagamentoPagas.getNumeroTitulo());
        tfdValor.setText(String.valueOf(formaPagamentoPagas.getValor()));
        tfdValorPago.setText(String.valueOf(formaPagamentoPagas.getValorPago()));
        tfdClienteNome.setText(formaPagamentoPagas.getCliente().getRazaoSocial());
        tfdFormaPagamentoNome.setText(formaPagamentoPagas.getFormaPagamento().getDescricao());
        tfdValorPago.setText(String.valueOf(formaPagamentoPagas.getValorPago()));

        if (formaPagamentoPagas.getQuitado() == 'T') {
            tfdSituacao.setText("QUITADO");
            tffValorAReceber.setEnabled(false);

            btnReceberTitulo.setEnabled(false);

        } else {
            tfdSituacao.setText("EM ABERTO");
            tffValorAReceber.setEnabled(true);
        }
        tfdDataEmissao.setText(formaPagamentoPagas.getDataEmissao());
        tfdDataPagamento.setText(formaPagamentoPagas.getDataPagamento());
        tfdDataVencimento.setText(formaPagamentoPagas.getVencimento());

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfdCodigo = new javax.swing.JTextField();
        tfdNumeroTitulo = new javax.swing.JTextField();
        tfdClienteNome = new javax.swing.JTextField();
        tfdValor = new javax.swing.JTextField();
        tfdFormaPagamentoNome = new javax.swing.JTextField();
        tfdSituacao = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfdDataEmissao = new javax.swing.JTextField();
        tfdDataVencimento = new javax.swing.JTextField();
        tfdDataPagamento = new javax.swing.JTextField();
        btnReceberTitulo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tffValorAReceber = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        tfdValorPago = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EasyPDV - Cadastro de títulos a receber");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro Título a receber", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 51, 255))); // NOI18N

        jLabel1.setText("Código:");

        jLabel2.setText("N° Título:");

        jLabel3.setText("Cliente:");

        jLabel4.setText("Valor:");

        jLabel5.setText("Forma de pagamento:");

        jLabel6.setText("Situação:");

        tfdCodigo.setEditable(false);

        tfdNumeroTitulo.setEditable(false);

        tfdClienteNome.setEditable(false);

        tfdValor.setEditable(false);

        tfdFormaPagamentoNome.setEditable(false);

        tfdSituacao.setEditable(false);

        jLabel7.setText("Data Emissao:");

        jLabel8.setText("Data Vencimento:");

        jLabel9.setText("Data pagamento:");

        tfdDataEmissao.setEditable(false);

        tfdDataVencimento.setEditable(false);

        tfdDataPagamento.setEditable(false);

        btnReceberTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Icon_money.png"))); // NOI18N
        btnReceberTitulo.setText("Receber Título");
        btnReceberTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceberTituloActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_Schutdown16.png"))); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Valor a receber:");

        tffValorAReceber.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabel12.setText("Valor pago:");

        tfdValorPago.setEditable(false);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_button_cancel.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReceberTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tffValorAReceber, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfdFormaPagamentoNome)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(34, 34, 34)
                                .addComponent(tfdClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfdValor, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdNumeroTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfdDataPagamento)
                                    .addComponent(tfdDataVencimento)
                                    .addComponent(tfdSituacao)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(tfdDataEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdNumeroTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfdDataEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tfdDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tfdDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfdSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfdClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfdFormaPagamentoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tffValorAReceber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnReceberTitulo)
                    .addComponent(btnExcluir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnReceberTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceberTituloActionPerformed
        //if (Double.parseDouble(tffValorAReceber.getText().replace(",", "."))>0) {
        try {
            formaPagamentoPagas.setAtivo('T');
            pagarTitulo();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "É preciso informar um valor para pagar o título");
        }

        listarTitulo();
    }//GEN-LAST:event_btnReceberTituloActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        formaPagamentoPagas.setAtivo('F');
        Date data = new Date();
        data.setDate(data.getDate());
        String dataFormatada = Formatacao.ajustaDataDMAJCalendar(data);
        formaPagamentoPagas.setDataPagamento(dataFormatada);

        FinanceiroReceberDAO financeiroPagamentoDAO = new FinanceiroReceberDAO();
        int retorno = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que quer excluir o título\n número :" + formaPagamentoPagas.getNumeroTitulo() + "\n"
                + " de valor: " + formaPagamentoPagas.getValor());
        if (retorno == 0) {
            if (financeiroPagamentoDAO.salvar(null, 0, formaPagamentoPagas)) {
                JOptionPane.showMessageDialog(rootPane, "Título excluído com sucesso!");
                dispose();

            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro ao excluir o título");
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed
    private void pagarTitulo() {
        if ((Double.parseDouble(tffValorAReceber.getText().replace(",", "."))) + (Double.parseDouble(tfdValorPago.getText().replace(",", "."))) >= Double.parseDouble(tfdValor.getText().replace(",", "."))) {
            formaPagamentoPagas.setQuitado('T');
            formaPagamentoPagas.setValorPago((Double.parseDouble(tffValorAReceber.getText().replace(",", "."))) + (Double.parseDouble(tfdValorPago.getText().replace(",", "."))));
            Date data = new Date();
            data.setDate(data.getDate());
            String dataFormatada = Formatacao.ajustaDataDMAJCalendar(data);
            formaPagamentoPagas.setDataPagamento(dataFormatada);
            FinanceiroReceberDAO financeiroPagamentoDAO = new FinanceiroReceberDAO();

            if (financeiroPagamentoDAO.salvar(null, 0, formaPagamentoPagas)) {
                JOptionPane.showMessageDialog(rootPane, "Pagamento do título registrado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro ao salvar pagamento do título");
            }

        } else {

            formaPagamentoPagas.setValorPago((Double.parseDouble(tffValorAReceber.getText().replace(",", "."))) + (Double.parseDouble(tfdValorPago.getText().replace(",", "."))));
            Date data = new Date();
            data.setDate(data.getDate());
            String dataFormatada = Formatacao.ajustaDataDMAJCalendar(data);
            formaPagamentoPagas.setDataPagamento(dataFormatada);
            FinanceiroReceberDAO financeiroPagamentoDAO = new FinanceiroReceberDAO();

            if (financeiroPagamentoDAO.salvar(null, 0, formaPagamentoPagas)) {
                JOptionPane.showMessageDialog(rootPane, "Pagamento do título registrado com sucesso!");
                tffValorAReceber.setText("");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro ao salvar pagamento do título");
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JdgCadastroFinanceiroReceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JdgCadastroFinanceiroReceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JdgCadastroFinanceiroReceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JdgCadastroFinanceiroReceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JdgCadastroFinanceiroReceber dialog = new JdgCadastroFinanceiroReceber(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnReceberTitulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfdClienteNome;
    private javax.swing.JTextField tfdCodigo;
    private javax.swing.JTextField tfdDataEmissao;
    private javax.swing.JTextField tfdDataPagamento;
    private javax.swing.JTextField tfdDataVencimento;
    private javax.swing.JTextField tfdFormaPagamentoNome;
    private javax.swing.JTextField tfdNumeroTitulo;
    private javax.swing.JTextField tfdSituacao;
    private javax.swing.JTextField tfdValor;
    private javax.swing.JTextField tfdValorPago;
    private javax.swing.JFormattedTextField tffValorAReceber;
    // End of variables declaration//GEN-END:variables
}
