/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import DAO.CidadeDAO;
import DAO.ClienteDAO;
import DAO.FaturamentoDAO;
import DAO.FinanceiroReceberDAO;
import apoio.ConexaoBD;
import apoio.Formatacao;
import apoio.Validacao;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import entidade.Cidade;
import entidade.Cliente;
import entidade.Faturamento;
import entidade.FaturamentoItem;
import entidade.FormaPagamento;
import entidade.FormaPagamentoPagas;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Mileto
 */
public class JdgListagemFinanceiroReceber extends javax.swing.JDialog {

    /**
     * Creates new form JdgListagemVendas
     */
    FormaPagamentoPagas formasPagas;
    Cliente cli;
    ArrayList<FormaPagamentoPagas> arrayFormasPagas;
    
    public JdgListagemFinanceiroReceber(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        FormaPagamentoPagas formasPagas = new FormaPagamentoPagas();
        Cidade cid = new Cidade();
        cli = new Cliente(cid);
        this.formasPagas = formasPagas;
        //fat.setFase('e');
        arrayFormasPagas = new ArrayList<>();
        //listarVendas();
        tfdBuscar.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        rbtFiltroData = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tffDataInicio = new com.toedter.calendar.JDateChooser();
        tffDataFim = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        rbtFinalizadas = new javax.swing.JRadioButton();
        rbtAbertos = new javax.swing.JRadioButton();
        btnRelatorios = new javax.swing.JButton();
        btnAcessarVenda = new javax.swing.JButton();
        btnCancelarVenda = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        tfdBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaTitulos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EasyPDV - Listagem de vendas");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listagem de Títulos a receber", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel1.setToolTipText("");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Período", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        rbtFiltroData.setText("Filtro de data");
        rbtFiltroData.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtFiltroDataItemStateChanged(evt);
            }
        });

        jLabel1.setText("Início:");

        jLabel2.setText("Fim:");

        tffDataInicio.setToolTipText("");
        tffDataInicio.setEnabled(false);
        tffDataInicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tffDataInicioKeyReleased(evt);
            }
        });

        tffDataFim.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tffDataInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rbtFiltroData, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addComponent(tffDataFim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtFiltroData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tffDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tffDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fase", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        rbtFinalizadas.setSelected(true);
        rbtFinalizadas.setText("Finalizadas");
        rbtFinalizadas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtFinalizadasItemStateChanged(evt);
            }
        });

        rbtAbertos.setText("Canceladas");
        rbtAbertos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtAbertosItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtFinalizadas)
                    .addComponent(rbtAbertos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtFinalizadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtAbertos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/print.png"))); // NOI18N
        btnRelatorios.setText("Relatórios");
        btnRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatoriosActionPerformed(evt);
            }
        });

        btnAcessarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Edit File-16.png"))); // NOI18N
        btnAcessarVenda.setText("Acessar Venda");
        btnAcessarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcessarVendaActionPerformed(evt);
            }
        });

        btnCancelarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconcancel3.png"))); // NOI18N
        btnCancelarVenda.setText("Cancelar Venda");
        btnCancelarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarVendaActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_Schutdown16.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        tfdBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfdBuscarKeyReleased(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Lupa3.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAcessarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfdBuscar)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfdBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAcessarVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelarVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRelatorios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vendas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N

        tblListaTitulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "N° Título", "Cliente", "Data Emissão", "Data Vencimento", "Data Pagamento", "Valor do Título", "Valor Pago"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListaTitulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListaTitulosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListaTitulos);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 993, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void listarTitulos() {
        
        if (rbtFinalizadas.isSelected() && rbtAbertos.isSelected()) {
            formasPagas.setQuitado('A');
        } else if (rbtFinalizadas.isSelected() && !rbtAbertos.isSelected()) {
            formasPagas.setQuitado('T');
        } else if (!rbtFinalizadas.isSelected() && rbtAbertos.isSelected()) {
            formasPagas.setQuitado('F');
        } else {
            formasPagas.setQuitado(' ');
        }
        
        try {
            //setar para tabela modelo de dados
            tblListaTitulos.setModel(this.obterDadosParaTabelaCompleto());
            tblListaTitulos.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblListaTitulos.getColumnModel().getColumn(1).setPreferredWidth(150);
            tblListaTitulos.getColumnModel().getColumn(2).setPreferredWidth(50);
            tblListaTitulos.getColumnModel().getColumn(3).setPreferredWidth(60);
            tblListaTitulos.getColumnModel().getColumn(4).setPreferredWidth(20);
            tblListaTitulos.getColumnModel().getColumn(5).setPreferredWidth(40);
            tblListaTitulos.getColumnModel().getColumn(6).setPreferredWidth(0);
            tblListaTitulos.getColumnModel().getColumn(7).setPreferredWidth(0);
            
        } catch (Exception ex) {
            Logger.getLogger(JdgListaFormaPagamento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private DefaultTableModel obterDadosParaTabelaCompleto() throws Exception {
        DefaultTableModel dtm = new DefaultTableModel() {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
//adiciona titulo para as colunas

        FinanceiroReceberDAO formasDAO = new FinanceiroReceberDAO();
        ArrayList<FormaPagamentoPagas> formas = formasDAO.consultar(formasPagas);

//        ClienteDAO cliDAO = new ClienteDAO();
//        ArrayList<Cliente> clientes = cliDAO.consultar(cliente);
        dtm.addColumn("N° TÍTULO");
        dtm.addColumn("CLIENTE");
        dtm.addColumn("DATA EMISSÃO");
        dtm.addColumn("DATA VENCIMENTO");
        dtm.addColumn("VALOR TÍTULO");
        dtm.addColumn("DATA PAGAMENTO");        
        dtm.addColumn("VALOR PAGO");
        dtm.addColumn("SITUAÇÃO");

        
        for (int i = 0; i < formas.size(); i++) {
            //popular tabela
            String fase = "";
            if (String.valueOf(formas.get(i).getQuitado()).equalsIgnoreCase("T")) {
                fase = "Encerrado";
            } else {
                fase = "Aberto";
            }
            
            dtm.addRow(new String[]{String.valueOf(formas.get(i).getNumeroTitulo()),
                String.valueOf(formas.get(i).getCliente().getRazaoSocial()),
                formas.get(i).getDataEmissao(),
                formas.get(i).getVencimento(),
                String.valueOf(formas.get(i).getValor()),
                
                String.valueOf(formas.get(i).getDataPagamento()),
                String.valueOf(formas.get(i).getValorPago()),
                fase,
            });
        }
//retorna o modelo
        return dtm;
    }
    

    private void rbtFiltroDataItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtFiltroDataItemStateChanged
        if (rbtFiltroData.isSelected()) {
            
            tffDataFim.setEnabled(true);
            tffDataInicio.setEnabled(true);
            
        } else {
            
            tffDataFim.setCalendar(null);
            tffDataInicio.setCalendar(null);
            tffDataFim.setEnabled(false);
            tffDataInicio.setEnabled(false);
            
        }

    }//GEN-LAST:event_rbtFiltroDataItemStateChanged

    private void tffDataInicioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tffDataInicioKeyReleased

    }//GEN-LAST:event_tffDataInicioKeyReleased

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        validarTipoDeBusca();
        

    }//GEN-LAST:event_btnBuscarActionPerformed
    private void buscar() {
//        if (tfdBuscar.getText().length() > 0) {
//            
//            cli.setRazaoSocial(tfdBuscar.getText());
//            formasPagas.setCliente(cli);
//            try {
//                formasPagas.setId(Integer.parseInt(tfdBuscar.getText()));
//                
//            } catch (Exception e) {
//                
//            }
//            
//        } else {
//            tfdBuscar.setText("");
//            cli.setRazaoSocial(tfdBuscar.getText());
//            formasPagas.setId(0);
//        }
//        if (tffDataInicio.getCalendar() != null && tffDataFim.getCalendar() != null) {
//            
//            String dataInicio = Formatacao.ajustaDataDMAJCalendar(tffDataInicio);
//            String dataFim = Formatacao.ajustaDataDMAJCalendar(tffDataFim);
//            fat.setDataEmissaoInicio(dataInicio);
//            fat.setDataEmissaoFim(dataFim);
//            listarTitulos();
//        } else {
//            fat.setDataEmissaoInicio(null);
//            fat.setDataEmissaoFim(null);
////            JOptionPane.showMessageDialog(rootPane, "entrou no else");
//            listarTitulos();
//        }
        listarTitulos();
    }
    
    private void validarTipoDeBusca() {
        
        if (tffDataInicio.getCalendar() != null && tffDataFim.getCalendar() != null) {
            try {
                if (Validacao.validadeFiltroDeData(tffDataInicio, tffDataFim)) {
                    buscar();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Filtro de data Incorreta");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Filtro de data Incorreta");
            }
            
        } else {
            buscar();
        }
        
    }
    private void btnCancelarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarVendaActionPerformed
//        FaturamentoDAO fatDAO = new FaturamentoDAO();
//        vendas = fatDAO.consultar(fat, cli);
//        try {
//            int op = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja cancelar a venda? \n"
//                    + "ID: " + vendas.get(tblListaVendas.getSelectedRow()).getId() + "\n"
//                    + "Cliente: " + vendas.get(tblListaVendas.getSelectedRow()).getCliente().getRazaoSocial()
//            );
//            
//            if (op == 0) {
//                try {
//                    
//                    cancelarVenda();
//                    
//                } catch (Exception ex) {
//                    Logger.getLogger(JdgPedidoVenda.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(rootPane, "Nenhuma Linha da tabela Selecionada");
//        }

    }//GEN-LAST:event_btnCancelarVendaActionPerformed

    private void btnAcessarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessarVendaActionPerformed
        acessarVenda();

    }//GEN-LAST:event_btnAcessarVendaActionPerformed

    private void tblListaTitulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaTitulosMouseClicked
        int row = tblListaTitulos.getSelectedRow();
        if (tblListaTitulos.getValueAt(row, 6) == "Cancelado") {
            btnCancelarVenda.setEnabled(false);
        } else {
            btnCancelarVenda.setEnabled(true);
        }
        
        if (evt.getClickCount() > 1) {
            int linhaSelecionada = tblListaTitulos.getSelectedRow();
            acessarVenda();
            
        }

    }//GEN-LAST:event_tblListaTitulosMouseClicked

    private void rbtAbertosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtAbertosItemStateChanged
        listarTitulos();
    }//GEN-LAST:event_rbtAbertosItemStateChanged

    private void rbtFinalizadasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtFinalizadasItemStateChanged
        listarTitulos();
    }//GEN-LAST:event_rbtFinalizadasItemStateChanged

    private void tfdBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdBuscarKeyReleased
        validarTipoDeBusca();
    }//GEN-LAST:event_tfdBuscarKeyReleased

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatoriosActionPerformed
//        try {
//            if (Validacao.validadeFiltroDeData(tffDataInicio, tffDataFim)) {
//                if (rbtAbertos.isSelected() || rbtFinalizadas.isSelected()) {
//                    
//                    buscar();
//
//
//                    JdgRelatoriosVendas relatorioVendas = new JdgRelatoriosVendas(null, false, fat);
//                    
//                    relatorioVendas.setVisible(true);
//                    
//                } else {
//                    JOptionPane.showMessageDialog(rootPane, "Nenhuma fase do pedido selecionada!\n para gerar o relatório precisa selecionar\numa fase ou mais");                    
//                }
//                
//            } else {
//                JOptionPane.showMessageDialog(rootPane, "Filtro de data Incorreta!\n para gerar relatório precisa informar um período");
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(rootPane, "Filtro de data Incorreta!\n para gerar relatório precisa informar um período");
//        }
//        
//        try {
//            // Compila o relatorio//
//
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Erro ao gerar relatório: " + e);
//            System.out.println(e);
//        }
//        

    }//GEN-LAST:event_btnRelatoriosActionPerformed
    
    private void acessarVenda() {
        formasPagas.setId(0);
        arrayFormasPagas.removeAll(arrayFormasPagas);
        int row = tblListaTitulos.getSelectedRow();
        FinanceiroReceberDAO finDAO = new FinanceiroReceberDAO();
        FormaPagamento formaPagamento = new FormaPagamento();
        
        arrayFormasPagas = finDAO.consultar(formasPagas);
        
        
        formaPagamento.setDescricao(arrayFormasPagas.get(row).getFormaPagamento().getDescricao());
        formasPagas.setFormaPagamento(formaPagamento);
        formasPagas.setId(arrayFormasPagas.get(row).getId());
        cli.setRazaoSocial(arrayFormasPagas.get(row).getCliente().getRazaoSocial());
        formasPagas.setQuitado(arrayFormasPagas.get(row).getQuitado());
        formasPagas.setDataEmissao(arrayFormasPagas.get(row).getDataEmissao());
        formasPagas.setDataPagamento(arrayFormasPagas.get(row).getDataPagamento());
        formasPagas.setVencimento(arrayFormasPagas.get(row).getVencimento());
        Faturamento fat = new Faturamento();
        //fat.setId(arrayFormasPagas.get(row).getFaturamento().getId());
        formasPagas.setNumeroTitulo(arrayFormasPagas.get(row).getNumeroTitulo());
        formasPagas.setValor(arrayFormasPagas.get(row).getValor());
        formasPagas.setValorPago(arrayFormasPagas.get(row).getValorPago());
        formasPagas.setCliente(cli);
        //JdgVendaRegistrada vendaRegistrada = new JdgVendaRegistrada(null, true, fat);
        //vendaRegistrada.setVisible(true);
        
        JdgCadastroFinanceiroReceber financeiroReceber = new JdgCadastroFinanceiroReceber(null, true, formasPagas);
        financeiroReceber.setVisible(true);
        
        formasPagas.setId(0);
        listarTitulos();
    }
    
    private void cancelarVenda() {
//        int row = tblListaVendas.getSelectedRow();
//        
//        fat.setId(vendas.get(row).getId());
//        
//        FaturamentoDAO fatDAO = new FaturamentoDAO();
//        if (fatDAO.salvar(fat, null, null)) {
//            JOptionPane.showMessageDialog(rootPane, "Cancelamento da venda realizado com sucesso!");
//            fat.setId(0);
//            listarTitulos();
//        } else {
//            JOptionPane.showMessageDialog(rootPane, "erro retornado pelo sistema:\nErro ao cancelar venda.");
//        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JdgListagemFinanceiroReceber.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JdgListagemFinanceiroReceber.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JdgListagemFinanceiroReceber.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JdgListagemFinanceiroReceber.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JdgListagemFinanceiroReceber dialog = new JdgListagemFinanceiroReceber(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcessarVenda;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelarVenda;
    private javax.swing.JButton btnRelatorios;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtAbertos;
    private javax.swing.JRadioButton rbtFiltroData;
    private javax.swing.JRadioButton rbtFinalizadas;
    private javax.swing.JTable tblListaTitulos;
    private javax.swing.JTextField tfdBuscar;
    private com.toedter.calendar.JDateChooser tffDataFim;
    private com.toedter.calendar.JDateChooser tffDataInicio;
    // End of variables declaration//GEN-END:variables
}
